---
accounts:
  name: Accounts
  description: My Online Accounts
  icon:
      class: fa-solid fa-users
  subitems:
  - name: Meta
    description: Social and developer networks
    icon:
      class: fa-brands fa-meta
    url: 
    subitems:
    - name: Instagram
      description: Follow me on Instagram
      icon:
        class: fa-brands fa-instagram
      url: https://www.instagram.com/kevinveenbirkenbach/
      identifier: kevinveenbirkenbach
      warning: Using software and platforms from the Meta corporation (e.g., Facebook, Instagram, WhatsApp) may compromise your data privacy and digital freedom due to centralized control, extensive data collection practices, and inconsistent moderation policies. These platforms often fail to adequately address harmful content, misinformation, and abuse.
    - name: Facebook
      description: Like my Facebook page
      icon:
        class: fa-brands fa-facebook
      url: https://www.facebook.com/kevinveenbirkenbach
  - link: navigation.header.contact.messenger
  - name: Carreer Profiles
    icon:
      class: fa-solid fa-user-tie
    subitems:
    - name: XING
      description: Visit my XING profile
      icon:
        class: bi bi-building
      url: https://www.xing.com/profile/Kevin_VeenBirkenbach
      
    - name: LinkedIn
      description: Connect on LinkedIn
      icon:
        class: bi bi-linkedin
      url: https://www.linkedin.com/in/kevinveenbirkenbach
      
  - name: Sports
    description: My sport activities
    icon:
      class: fa-solid fa-running
    url: 
    subitems:
    - name: Garmin
      description: My Garmin activities
      icon:
        class: fa-solid fa-person-running
      url: https://s.veen.world/garmin
      
    - name: Eversports
      description: My Eversports sessions
      icon:
        class: fa-solid fa-dumbbell
      url: https://s.veen.world/eversports
      
  - name: Duolingo
    description: Learn with me on Duolingo
    icon:
      class: fa-solid fa-language
    url: https://www.duolingo.com/profile/kevinbirkenbach
    
  - name: Spotify
    description: Listen to my playlists
    icon:
      class: fa-brands fa-spotify
    url: https://open.spotify.com/user/31vebfzbjf3p7oualis76qfpr5ty
    
  - name: Patreon
    description: Support me on Patreon
    icon:
      class: fa-brands fa-patreon
    url: https://patreon.com/kevinveenbirkenbach
    
  - name: Discourse
    description: Follow me on Discourse
    icon:
      class: fa-brands fa-discourse
    url: https://forum.veen.world/u/kevinveenbirkenbach
    

cards:
- icon: 
    source: https://cloud.veen.world/s/logo_agile_coach_512x512/download
  title: Agile Coach
  text: I lead agile transformations and improve team dynamics through Scrum, DevOps,
    and Agile Coaching. My goal is to enhance collaboration and efficiency in organizations,
    ensuring agile principles are effectively implemented for sustainable success.
  url: https://www.agile-coach.world
  link_text: www.agile-coach.world
- icon: 
    source: https://cloud.veen.world/s/logo_personal_coach_512x512/download
  title: Personal Coach
  text: Offering personalized coaching for growth and development, I utilize a blend
    of hypnotherapy, mediation, and holistic techniques. My approach is tailored to
    help you achieve personal and professional milestones, fostering holistic well-being.
  url: https://www.personalcoach.berlin
  link_text: www.personalcoach.berlin
- icon: 
    source: https://cloud.veen.world/s/logo_yachtmaster_512x512/download
  title: Yachtmaster
  text: As a Yachtmaster, I provide comprehensive sailing education, yacht delivery,
    and voyage planning services. Whether you're learning to sail or need an experienced
    skipper, my expertise ensures a safe and enjoyable experience on the water.
  url: https://www.yachtmaster.world
  link_text: www.yachtmaster.world
- icon: 
    source: https://cloud.veen.world/s/logo_polymath_512x512/download
  title: Polymath
  text: I support the evaluation and execution of complex cross-domain projects, offering
    insights across land, sea, sky, and digital realms. My expertise helps clients
    navigate and succeed in multifaceted environments with strategic precision.
  url: https://www.crossdomain.consulting/
  link_text: www.crossdomain.consulting
- icon: 
    source: https://cloud.veen.world/s/logo_cybermaster_512x512/download
  title: Cybermaster
  text: Specializing in open-source IT solutions for German SMBs, I focus on automation,
    security, and reliability. My services are designed to create robust infrastructures
    that streamline operations and safeguard digital assets.
  url: https://www.cybermaster.space
  link_text: www.cybermaster.space
- icon: 
    source: https://cloud.veen.world/s/logo_prompt_master_512x512/download
  title: Prompt Engineer
  text: Leveraging AI's power, I specialize in crafting custom prompts and creative
    content for AI-driven applications. My services are aimed at businesses, creatives,
    and researchers looking to harness AI technology for innovation, efficiency, and
    exploring new possibilities.
  url: https://promptmaster.nexus
  link_text: www.promptmaster.nexus
- icon: 
    source: https://cloud.veen.world/s/logo_mediator_512x512/download
  title: Mediator
  text: Specializing in resolving interpersonal and business conflicts with empathy
    and neutrality, I facilitate open communication to achieve lasting agreements
    and strengthen relationships. My mediation services are designed for individuals,
    teams, and organizations to foster a harmonious and productive environment.
  url: https://www.mediator.veen.world
  link_text: www.mediator.veen.world
- icon: 
    source: https://cloud.veen.world/s/logo_hypnotherapist_512x512/download
  title: Hypnotherapist
  text: As a certified Hypnotherapist, I offer tailored sessions to address mental
    and emotional challenges through hypnosis. My approach helps unlock the subconscious
    to overcome negative beliefs and stress, empowering you to activate self-healing
    and embrace positive life changes.
  url: https://www.hypno.veen.world
  link_text: www.hypno.veen.world
- icon: 
    source: https://cloud.veen.world/s/logo_skydiver_512x512/download
  title: Aerospace Consultant
  text: As an Aerospace Consultant with aviation credentials, including a Sport Pilot
    License for Parachutes, and a Restricted Radiotelephony and Operator's Certificate
    I deliver expert consulting services. Currently training for my Private Pilot
    License, I specialize in guiding clients through aviation regulations, safety
    standards, and operational efficiency.
  url: 
  link_text: Website under construction
- icon: 
    source: https://cloud.veen.world/s/logo_hunter_512x512/download
  title: Wildlife Expert
  text: As a certified hunter and wildlife coach, I offer educational programs, nature
    walks, survival trainings, and photo expeditions, merging ecological knowledge
    with nature respect. My goal is to foster sustainable conservation and enhance
    appreciation for the natural world through responsible practices.
  url: 
  link_text: Website under construction
- icon: 
    source: https://cloud.veen.world/s/logo_diver_512x512/download
  title: Master Diver
  text: As a certified master diver with trainings in various specialties, I offer
    diving instruction, underwater photography, and guided dive tours. My experience
    ensures safe and enriching underwater adventures, highlighting marine conservation
    and the wonders of aquatic ecosystems.
  url: 
  link_text: Website under construction
- icon: 
    source: https://cloud.veen.world/s/logo_massage_therapist_512x512/download
  title: Massage Therapist
  text: Certified in Tantra Massage, I offer unique full-body rituals to awaken senses
    and harmonize body and mind. My sessions, a blend of ancient Tantra and modern
    relaxation, focus on energy flow, personal growth, and spiritual awakening.
  url: 
  link_text: Website under construction
company:
  titel: Kevin Veen-Birkenbach
  subtitel: Consulting and Coaching Solutions
  logo:
    source: https://cloud.veen.world/s/logo_face_512x512/download
  favicon:
    source: https://cloud.veen.world/s/veen_world_favicon/download
  address:
    street: Afrikanische Straße 43
    postal_code: DE-13351
    city: Berlin
    country: Germany
  imprint_url: https://s.veen.world/imprint
navigation:
  header:
  - name: Microblog
    description: Read my microblogs
    icon:
        class: fa-brands fa-mastodon
    url: https://microblog.veen.world/@kevinveenbirkenbach
    
  - name: Pictures
    description: View my photo gallery
    icon:
        class: fa-solid fa-camera
    url: https://picture.veen.world/kevinveenbirkenbach
    
  - name: Videos
    description: Watch my videos
    icon:
        class: fa-solid fa-video
    url: https://video.veen.world/a/kevinveenbirkenbach
    
  - name: Blog
    description: Read my blog
    icon:
        class: fa-solid fa-blog
    url: https://blog.veen.world
    
  - name: Code
    icon:
        class: fa-solid fa-laptop-code
    description: Check out my Code
    subitems:
    - name: Github
      description: View my GitHub profile
      icon:
        class: bi bi-github
      url: https://github.com/kevinveenbirkenbach
      
    - name: Gitea
      description: Explore my code repositories
      icon:
        class: fa-solid fa-code
      url: https://git.veen.world/kevinveenbirkenbach
      
  - name: Contact
    description: Get in touch
    icon:
        class: fa-solid fa-envelope
    subitems:
    - name: Email
      description: Send me an email
      icon:
        class: fa-solid fa-envelope
      url: mailto:kevin@veen.world
      identifier: kevin@veen.world
      alternatives:
        - link: navigation.header.contact.messenger.matrix
    - name: Mobile
      description: Call me
      icon:
        class: fa-solid fa-phone
      url: "tel:+491781798023"
      identifier: "+491781798023"
      target: _top
    - name: Encrypted Email (PGP)
      description: Download my PGP key
      icon:
        class: fa-solid fa-key
      url: https://s.veen.world/pgp
      identifier: kevin@veen.world
      info: |
        #### Why Use PGP?
        PGP ensures your email content stays private, protecting against surveillance, data breaches, and unauthorized access.

        #### Protect Your Privacy
        In an age of mass data collection, PGP empowers you to communicate securely and assert control over your information. For insights on protecting your digital rights, visit the [Electronic Frontier Foundation (EFF)](https://www.eff.org/).

        #### Build Trust
        Encrypting emails demonstrates a commitment to privacy and security, fostering trust in professional and personal communication.

        #### Stand for Security
        Using PGP is more than a tool—it's a statement about valuing freedom, privacy, and the security of digital communication. Explore the principles of secure communication with [privacy guides](https://privacyguides.org/).
    - name: Messenger
      description: Social and developer networks
      icon:
        class: fa-solid fa-comments
      subitems: 
      - name: Matrix
        description: Chat with me on Matrix
        icon:
          class: fa-solid fa-cubes
        identifier: "@kevinveenbirkenbach:veen.world"
        info: |
          #### Why Use Matrix?
          Matrix is a secure, decentralized communication platform that ensures privacy and control over your data. Learn more about [Matrix](https://matrix.org/).

          #### Privacy and Security
          End-to-end encryption keeps your conversations private and secure.

          #### Decentralized and Open
          Matrix's federated network means you can host your own server or use any provider while staying connected.

          #### A Movement for Digital Freedom
          By using Matrix, you support open, transparent, and secure communication.
      - name: Signal
        description: Message me on Signal
        icon:
          class: fa-brands fa-signal-messenger
        identifier: "+491781798023"
        warning: Signal is not hosted by me!
        alternatives:
          - link: navigation.header.contact.messenger.matrix
      - name: Telegram
        description: Message me on Telegram
        icon:
          class: fa-brands fa-telegram
        target: _blank
        url: https://t.me/kevinveenbirkenbach
        identifier: kevinveenbirkenbach
        warning: Telegram is not hosted by me!
        alternatives:
          - link: navigation.header.contact.messenger.matrix
      - name: WhatsApp
        description: Chat with me on WhatsApp
        icon:
          class: fa-brands fa-whatsapp
        url: https://wa.me/491781798023
        identifier: "+491781798023"
        info: Consider using decentralized and privacy-respecting alternatives to maintain control over your data, improve security, and foster healthier online interactions.
        alternatives:
          - link: navigation.header.contact.messenger.matrix
          - link: navigation.header.contact.messenger.signal
          - link: navigation.header.contact.messenger.telegram

  footer:
  - link: accounts
  - name: Solution Hub
    description: Curated collection of self hosted tools
    icon:
        class: fa-solid fa-network-wired
    url: 
    subitems:
    - name: Community
      description: Tools to manage the community
      icon:
          class: fa-solid fa-users
      subitems:
      - name: Forum
        description: Join the discussion
        icon:
          class: fa-brands fa-discourse
        url: https://forum.veen.world/
      - name: Learning Platform
        description: Learn with my academy
        icon:
          class: fa-solid fa-graduation-cap
        url: https://academy.veen.world/
      - name: Newsletter
        description: Subscribe to my newsletter
        icon:
          class: fa-solid fa-envelope-open-text
        url: https://newsletter.veen.world/subscription/form
    - name: Project Management
      description: Project Management Tools
      icon:
          class: fa-solid fa-chart-line
      subitems:
      - name: Open Project
        description: Explore my projects
        icon:
          class: fa-solid fa-tasks
        url: https://project.veen.world/
        
      - name: Taiga
        description: View my Kanban board
        icon:
          class: bi bi-clipboard2-check-fill
        url: https://kanban.veen.world/
        
    - name: Matomo
      description: Analyze with Matomo
      icon:
        class: fa-solid fa-chart-simple
      url: https://matomo.veen.world/
      
    - name: Baserow
      description: Organize with Baserow
      icon:
        class: fa-solid fa-table
      url: https://baserow.veen.world/
    - name: Communication
      icon:
        class: fa-solid fa-comments
      subitems:
      - name: Elements
        description: Chat with me
        icon:
          class: fa-solid fa-comment
        url: https://element.veen.world/
        
      - name: Big Blue Button
        description: Join live events
        icon:
          class: fa-solid fa-video
        url: https://meet.veen.world/
        
      - name: Mailu
        description: Send me a mail
        icon:
          class: fa-solid fa-envelope
        url: https://mail.veen.world/      
    - name: Yourls
      description: Find my curated links
      icon:
        class: bi bi-link
      url: https://s.veen.world/admin/
      
    - name: Nextcloud
      description: Access my cloud storage
      icon:
        class: fa-solid fa-cloud
      url: https://cloud.veen.world/
      
  - name: Logbooks
    description: My activity logs
    icon:
        class: fa-solid fa-book
    url: 
    subitems:
    - name: Skydiver
      description: View my skydiving logs
      icon:
        class: fa-solid fa-parachute-box
      url: https://s.veen.world/skydiverlog
      
    - name: Skipper
      description: See my sailing records
      icon:
        class: fa-solid fa-sailboat
      url: https://s.veen.world/meilenbuch
      
    - name: Diver
      description: Check my diving logs
      icon:
        class: fa-solid fa-fish
      url: https://s.veen.world/diverlog
      
    - name: Pilot
      description: Review my flight logs
      icon:
        class: fa-solid fa-plane
      url: https://s.veen.world/pilotlog
      
    - name: Nature
      description: Explore my nature logs
      icon:
        class: fa-solid fa-tree
      url: https://s.veen.world/naturejournal
  - name: Vita
    description: View my CV
    icon:
        class: fa-solid fa-file-lines
    url: https://s.veen.world/lebenslauf
  - name: Certificates
    description: View my certifications and degrees
    icon:
        class: fa-solid fa-graduation-cap
    url: https://s.veen.world/lebenslauf
    
  - name: Imprint
    icon:
        class: fa-solid fa-scale-balanced
    url: https://s.veen.world/imprint
